version: 2
jobs:
  build:
    working_directory: ~/myapp/whishlist
    docker:
      - image: circleci/node:12.18.2-browsers
    steps:
      - checkout:
          path: ~/myapp
      - restore_cache:
          key: whishlist-{{ .branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_change:
          key: whishlist-{{ .branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --progress=false --watch=false --browser=ChromeHeadLessCI
